/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package View;

import java.sql.Connection;
import java.sql.DriverManager;
import javax.swing.JOptionPane;
import net.sf.jasperreports.engine.JasperCompileManager;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.engine.JasperReport;
import net.sf.jasperreports.engine.design.JRDesignQuery;
import net.sf.jasperreports.engine.design.JasperDesign;
import net.sf.jasperreports.engine.xml.JRXmlLoader;
import net.sf.jasperreports.view.JasperViewer;

/**
 *
 * @author Yasiru
 */
public class report extends javax.swing.JFrame {

    /**
     * Creates new form report
     */
    public report() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btn_Donor = new javax.swing.JButton();
        btn_Admin = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        lbl_Donors = new javax.swing.JLabel();
        lbl_Organization = new javax.swing.JLabel();
        btn_Organization = new javax.swing.JButton();
        btn_Medicalstaff = new javax.swing.JButton();
        lbl_Medicalstaff = new javax.swing.JLabel();
        lbl_Admin = new javax.swing.JLabel();
        lbl_Storage = new javax.swing.JLabel();
        lbl_Donation = new javax.swing.JLabel();
        btnDonation = new javax.swing.JButton();
        lbl_Transcation = new javax.swing.JLabel();
        btn_Transcation = new javax.swing.JButton();
        lbl_Appointment = new javax.swing.JLabel();
        btn_DonorAppointment = new javax.swing.JButton();
        lbl_DonorApp = new javax.swing.JLabel();
        lbl_Organizationapp = new javax.swing.JLabel();
        btn_AppointmentOrganization = new javax.swing.JButton();
        lbl_Footer = new javax.swing.JLabel();
        lbl_logo = new javax.swing.JLabel();
        btnStorage = new javax.swing.JButton();
        btn_back = new javax.swing.JButton();
        lbl_Wallpaper = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(900, 750));
        setMinimumSize(new java.awt.Dimension(900, 750));
        setPreferredSize(new java.awt.Dimension(900, 750));
        setSize(new java.awt.Dimension(900, 750));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btn_Donor.setBackground(new java.awt.Color(255, 255, 153));
        btn_Donor.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btn_Donor.setText("Click Here");
        btn_Donor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_DonorActionPerformed(evt);
            }
        });
        getContentPane().add(btn_Donor, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 150, -1, 40));

        btn_Admin.setBackground(new java.awt.Color(153, 255, 204));
        btn_Admin.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btn_Admin.setText("Click Here");
        btn_Admin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_AdminActionPerformed(evt);
            }
        });
        getContentPane().add(btn_Admin, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 530, 100, 40));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel1.setText("Admin Report Panel");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 10, 349, 46));

        lbl_Donors.setFont(new java.awt.Font("Goudy Old Style", 1, 24)); // NOI18N
        lbl_Donors.setText("Donors Full Details Report");
        getContentPane().add(lbl_Donors, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 100, 265, -1));

        lbl_Organization.setFont(new java.awt.Font("Goudy Old Style", 1, 24)); // NOI18N
        lbl_Organization.setText("Organizations Full Detail Report");
        getContentPane().add(lbl_Organization, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 230, 317, -1));

        btn_Organization.setBackground(new java.awt.Color(102, 153, 255));
        btn_Organization.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btn_Organization.setText("Click Here");
        btn_Organization.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_OrganizationActionPerformed(evt);
            }
        });
        getContentPane().add(btn_Organization, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 280, -1, 40));

        btn_Medicalstaff.setBackground(new java.awt.Color(153, 255, 153));
        btn_Medicalstaff.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btn_Medicalstaff.setText("Click Here");
        btn_Medicalstaff.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_MedicalstaffActionPerformed(evt);
            }
        });
        getContentPane().add(btn_Medicalstaff, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 420, 100, 40));

        lbl_Medicalstaff.setFont(new java.awt.Font("Goudy Old Style", 1, 24)); // NOI18N
        lbl_Medicalstaff.setText("Medical Staff Full Details Report");
        getContentPane().add(lbl_Medicalstaff, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 360, 330, -1));

        lbl_Admin.setFont(new java.awt.Font("Goudy Old Style", 1, 24)); // NOI18N
        lbl_Admin.setText("Admin Full Detail Report");
        getContentPane().add(lbl_Admin, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 480, 270, -1));

        lbl_Storage.setFont(new java.awt.Font("Goudy Old Style", 1, 24)); // NOI18N
        lbl_Storage.setText("Storage Full Detail Report");
        getContentPane().add(lbl_Storage, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 100, 310, 30));

        lbl_Donation.setFont(new java.awt.Font("Goudy Old Style", 1, 24)); // NOI18N
        lbl_Donation.setText("Donationa Full Details Report");
        getContentPane().add(lbl_Donation, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 230, 300, -1));

        btnDonation.setBackground(new java.awt.Color(0, 204, 204));
        btnDonation.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnDonation.setText("Click Here");
        btnDonation.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDonationActionPerformed(evt);
            }
        });
        getContentPane().add(btnDonation, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 270, -1, 40));

        lbl_Transcation.setFont(new java.awt.Font("Goudy Old Style", 1, 24)); // NOI18N
        lbl_Transcation.setText("Transcation Full Details Report");
        getContentPane().add(lbl_Transcation, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 360, 310, -1));

        btn_Transcation.setBackground(new java.awt.Color(255, 153, 255));
        btn_Transcation.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btn_Transcation.setText("Click Here");
        btn_Transcation.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_TranscationActionPerformed(evt);
            }
        });
        getContentPane().add(btn_Transcation, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 400, -1, 40));

        lbl_Appointment.setFont(new java.awt.Font("Goudy Old Style", 1, 24)); // NOI18N
        lbl_Appointment.setText("Appointment full Details Report");
        getContentPane().add(lbl_Appointment, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 470, 320, -1));

        btn_DonorAppointment.setBackground(new java.awt.Color(255, 255, 153));
        btn_DonorAppointment.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btn_DonorAppointment.setText("Click Here");
        btn_DonorAppointment.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_DonorAppointmentActionPerformed(evt);
            }
        });
        getContentPane().add(btn_DonorAppointment, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 560, -1, 40));

        lbl_DonorApp.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lbl_DonorApp.setText("Donor Appoinment");
        getContentPane().add(lbl_DonorApp, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 520, -1, 20));

        lbl_Organizationapp.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lbl_Organizationapp.setText("Organization Requests");
        getContentPane().add(lbl_Organizationapp, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 520, -1, -1));

        btn_AppointmentOrganization.setBackground(new java.awt.Color(153, 255, 153));
        btn_AppointmentOrganization.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btn_AppointmentOrganization.setText("Click Here");
        btn_AppointmentOrganization.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_AppointmentOrganizationActionPerformed(evt);
            }
        });
        getContentPane().add(btn_AppointmentOrganization, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 560, 100, 40));

        lbl_Footer.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lbl_Footer.setText("National Blood Bank @ National Blood Transfusion Service");
        getContentPane().add(lbl_Footer, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 680, 410, -1));

        lbl_logo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/Logo_size_3.png"))); // NOI18N
        getContentPane().add(lbl_logo, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 660, 50, 50));

        btnStorage.setBackground(new java.awt.Color(204, 255, 204));
        btnStorage.setText("Click Here");
        btnStorage.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnStorageActionPerformed(evt);
            }
        });
        getContentPane().add(btnStorage, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 150, 90, 40));

        btn_back.setFont(new java.awt.Font("Segoe UI Black", 1, 36)); // NOI18N
        btn_back.setText("Back");
        btn_back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_backActionPerformed(evt);
            }
        });
        getContentPane().add(btn_back, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 620, 130, 70));

        lbl_Wallpaper.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/reportpage.png"))); // NOI18N
        getContentPane().add(lbl_Wallpaper, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 900, 750));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btn_DonorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_DonorActionPerformed
        // TODO add your handling code here:
         try
        {
            String dbpath="jdbc:mysql://localhost:3306/NationalBloodBank";
            Connection con=DriverManager.getConnection(dbpath,"root","DdCya995142@4681");
            
            JasperDesign design=JRXmlLoader.load("C:\\Users\\Yasiru\\Desktop\\BloodBankManagementSystem\\src\\View\\Donors.jrxml");
            String query="Select * from Donor";
            JRDesignQuery designquery=new JRDesignQuery();
            designquery.setText(query);
            design.setQuery(designquery);
            JasperReport report=JasperCompileManager.compileReport(design);
            JasperPrint print=JasperFillManager.fillReport(report, null,con);
            JasperViewer.viewReport(print);
            
            
            
        }
        catch(Exception e)
        {
            JOptionPane.showMessageDialog(null,e.getMessage());
        }
    }//GEN-LAST:event_btn_DonorActionPerformed

    private void btn_AdminActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_AdminActionPerformed
        // TODO add your handling code here:
          try
        {
            String dbpath="jdbc:mysql://localhost:3306/NationalBloodBank";
            Connection con=DriverManager.getConnection(dbpath,"root","DdCya995142@4681");
            
            JasperDesign design=JRXmlLoader.load("C:\\Users\\Yasiru\\Desktop\\BloodBankManagementSystem\\src\\View\\Admin.jrxml");
            String query="Select * from Admin";
            JRDesignQuery designquery=new JRDesignQuery();
            designquery.setText(query);
            design.setQuery(designquery);
            JasperReport report=JasperCompileManager.compileReport(design);
            JasperPrint print=JasperFillManager.fillReport(report, null,con);
            JasperViewer.viewReport(print);
              
        }
        catch(Exception e)
        {
            JOptionPane.showMessageDialog(null,e.getMessage());
        }
    }//GEN-LAST:event_btn_AdminActionPerformed

    private void btn_OrganizationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_OrganizationActionPerformed
        // TODO add your handling code here:
         try
        {
            String dbpath="jdbc:mysql://localhost:3306/NationalBloodBank";
            Connection con=DriverManager.getConnection(dbpath,"root","DdCya995142@4681");
            
            JasperDesign design=JRXmlLoader.load("C:\\Users\\Yasiru\\Desktop\\BloodBankManagementSystem\\src\\View\\Organization.jrxml");
            String query="Select * from Organization";
            JRDesignQuery designquery=new JRDesignQuery();
            designquery.setText(query);
            design.setQuery(designquery);
            JasperReport report=JasperCompileManager.compileReport(design);
            JasperPrint print=JasperFillManager.fillReport(report, null,con);
            JasperViewer.viewReport(print);
            
            
            
        }
        catch(Exception e)
        {
            JOptionPane.showMessageDialog(null,e.getMessage());
        }
    }//GEN-LAST:event_btn_OrganizationActionPerformed

    private void btn_MedicalstaffActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_MedicalstaffActionPerformed
        // TODO add your handling code here:
          try
        {
            String dbpath="jdbc:mysql://localhost:3306/NationalBloodBank";
            Connection con=DriverManager.getConnection(dbpath,"root","DdCya995142@4681");
            
            JasperDesign design=JRXmlLoader.load("C:\\Users\\Yasiru\\Desktop\\BloodBankManagementSystem\\src\\View\\MedicalStaff.jrxml");
            String query="Select * from MedicalStaff";
            JRDesignQuery designquery=new JRDesignQuery();
            designquery.setText(query);
            design.setQuery(designquery);
            JasperReport report=JasperCompileManager.compileReport(design);
            JasperPrint print=JasperFillManager.fillReport(report, null,con);
            JasperViewer.viewReport(print);
            
            
            
        }
        catch(Exception e)
        {
            JOptionPane.showMessageDialog(null,e.getMessage());
        }
    }//GEN-LAST:event_btn_MedicalstaffActionPerformed

    private void btnStorageActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnStorageActionPerformed
        // TODO add your handling code here:
        
          try
        {
            String dbpath="jdbc:mysql://localhost:3306/NationalBloodBank";
            Connection con=DriverManager.getConnection(dbpath,"root","DdCya995142@4681");
            
            JasperDesign design=JRXmlLoader.load("C:\\Users\\Yasiru\\Desktop\\BloodBankManagementSystem\\src\\View\\Storage.jrxml");
            String query="Select * from storage";
            JRDesignQuery designquery=new JRDesignQuery();
            designquery.setText(query);
            design.setQuery(designquery);
            JasperReport report=JasperCompileManager.compileReport(design);
            JasperPrint print=JasperFillManager.fillReport(report, null,con);
            JasperViewer.viewReport(print);
            
            
            
        }
        catch(Exception e)
        {
            JOptionPane.showMessageDialog(null,e.getMessage());
        }
    }//GEN-LAST:event_btnStorageActionPerformed

    private void btnDonationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDonationActionPerformed
        // TODO add your handling code here:
            try
        {
            String dbpath="jdbc:mysql://localhost:3306/NationalBloodBank";
            Connection con=DriverManager.getConnection(dbpath,"root","DdCya995142@4681");
            
            JasperDesign design=JRXmlLoader.load("C:\\Users\\Yasiru\\Desktop\\BloodBankManagementSystem\\src\\View\\Donation.jrxml");
            String query="Select * from Donation";
            JRDesignQuery designquery=new JRDesignQuery();
            designquery.setText(query);
            design.setQuery(designquery);
            JasperReport report=JasperCompileManager.compileReport(design);
            JasperPrint print=JasperFillManager.fillReport(report, null,con);
            JasperViewer.viewReport(print);
            
            
            
        }
        catch(Exception e)
        {
            JOptionPane.showMessageDialog(null,e.getMessage());
        }
    }//GEN-LAST:event_btnDonationActionPerformed

    private void btn_TranscationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_TranscationActionPerformed
        // TODO add your handling code here:
                try
        {
            String dbpath="jdbc:mysql://localhost:3306/NationalBloodBank";
            Connection con=DriverManager.getConnection(dbpath,"root","DdCya995142@4681");
            
            JasperDesign design=JRXmlLoader.load("C:\\Users\\Yasiru\\Desktop\\BloodBankManagementSystem\\src\\View\\Transcation.jrxml");
            String query="Select * from Transcation";
            JRDesignQuery designquery=new JRDesignQuery();
            designquery.setText(query);
            design.setQuery(designquery);
            JasperReport report=JasperCompileManager.compileReport(design);
            JasperPrint print=JasperFillManager.fillReport(report, null,con);
            JasperViewer.viewReport(print);
            
            
            
        }
        catch(Exception e)
        {
            JOptionPane.showMessageDialog(null,e.getMessage());
        }
    }//GEN-LAST:event_btn_TranscationActionPerformed

    private void btn_DonorAppointmentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_DonorAppointmentActionPerformed
        // TODO add your handling code here:
                 try
        {
            String dbpath="jdbc:mysql://localhost:3306/NationalBloodBank";
            Connection con=DriverManager.getConnection(dbpath,"root","DdCya995142@4681");
            
            JasperDesign design=JRXmlLoader.load("C:\\Users\\Yasiru\\Desktop\\BloodBankManagementSystem\\src\\View\\DonorAppointment.jrxml");
            String query="Select * from donorappointment";
            JRDesignQuery designquery=new JRDesignQuery();
            designquery.setText(query);
            design.setQuery(designquery);
            JasperReport report=JasperCompileManager.compileReport(design);
            JasperPrint print=JasperFillManager.fillReport(report, null,con);
            JasperViewer.viewReport(print);
            
            
            
        }
        catch(Exception e)
        {
            JOptionPane.showMessageDialog(null,e.getMessage());
        }
    }//GEN-LAST:event_btn_DonorAppointmentActionPerformed

    private void btn_AppointmentOrganizationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_AppointmentOrganizationActionPerformed
        // TODO add your handling code here:
                  try
        {
            String dbpath="jdbc:mysql://localhost:3306/NationalBloodBank";
            Connection con=DriverManager.getConnection(dbpath,"root","DdCya995142@4681");
            
            JasperDesign design=JRXmlLoader.load("C:\\Users\\Yasiru\\Desktop\\BloodBankManagementSystem\\src\\View\\OrganizationAppointment.jrxml");
            String query="Select * from donororganization";
            JRDesignQuery designquery=new JRDesignQuery();
            designquery.setText(query);
            design.setQuery(designquery);
            JasperReport report=JasperCompileManager.compileReport(design);
            JasperPrint print=JasperFillManager.fillReport(report, null,con);
            JasperViewer.viewReport(print);
            
            
            
        }
        catch(Exception e)
        {
            JOptionPane.showMessageDialog(null,e.getMessage());
        }
    }//GEN-LAST:event_btn_AppointmentOrganizationActionPerformed

    private void btn_backActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_backActionPerformed
        // TODO add your handling code here:
        V_home_admin vc =new V_home_admin();
        vc.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btn_backActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(report.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(report.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(report.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(report.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new report().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDonation;
    private javax.swing.JButton btnStorage;
    private javax.swing.JButton btn_Admin;
    private javax.swing.JButton btn_AppointmentOrganization;
    private javax.swing.JButton btn_Donor;
    private javax.swing.JButton btn_DonorAppointment;
    private javax.swing.JButton btn_Medicalstaff;
    private javax.swing.JButton btn_Organization;
    private javax.swing.JButton btn_Transcation;
    private javax.swing.JButton btn_back;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel lbl_Admin;
    private javax.swing.JLabel lbl_Appointment;
    private javax.swing.JLabel lbl_Donation;
    private javax.swing.JLabel lbl_DonorApp;
    private javax.swing.JLabel lbl_Donors;
    private javax.swing.JLabel lbl_Footer;
    private javax.swing.JLabel lbl_Medicalstaff;
    private javax.swing.JLabel lbl_Organization;
    private javax.swing.JLabel lbl_Organizationapp;
    private javax.swing.JLabel lbl_Storage;
    private javax.swing.JLabel lbl_Transcation;
    private javax.swing.JLabel lbl_Wallpaper;
    private javax.swing.JLabel lbl_logo;
    // End of variables declaration//GEN-END:variables
}
