/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package View;

/**
 *
 * @author Yasiru
 */
public class V_About_us extends javax.swing.JFrame {

    /**
     * Creates new form V_About_us
     */
    public V_About_us() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        lbl_Vision = new javax.swing.JLabel();
        lbl_mission = new javax.swing.JLabel();
        lbl_wallpaper = new javax.swing.JLabel();
        jMenuBarAbout = new javax.swing.JMenuBar();
        jMenuBack = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(900, 600));
        setMinimumSize(new java.awt.Dimension(900, 600));
        setPreferredSize(new java.awt.Dimension(900, 600));
        setResizable(false);
        setSize(new java.awt.Dimension(900, 600));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setBackground(new java.awt.Color(255, 0, 0));
        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 0, 0));
        jLabel1.setText("About Us");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 10, 190, 41));

        lbl_Vision.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        lbl_Vision.setText("<html>\n<h1>Vision</h1>\n<p>To Be a unique model For the world securing quality assured Blood Service,through a nationally coordinated system</p>\n</html>");
        getContentPane().add(lbl_Vision, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 110, 760, 190));

        lbl_mission.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        lbl_mission.setText("<html>\n<h1>Our Mission</h1>\n<p> To ensure the quality,safety,adequacy and cost effectiveness of the blood supply and related laboratory,Clinical,academic and research services in accordance with national requirements and WHO recommendations <p>\n<html>");
        getContentPane().add(lbl_mission, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 310, 760, 200));

        lbl_wallpaper.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/aboutus.png"))); // NOI18N
        getContentPane().add(lbl_wallpaper, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 900, 560));

        jMenuBack.setText("  Back  ");
        jMenuBack.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jMenuBack.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenuBackMouseClicked(evt);
            }
        });
        jMenuBarAbout.add(jMenuBack);

        setJMenuBar(jMenuBarAbout);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuBackMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenuBackMouseClicked
        // TODO add your handling code here:
        V_Home_page hs=new V_Home_page();
        hs.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jMenuBackMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(V_About_us.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(V_About_us.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(V_About_us.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(V_About_us.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new V_About_us().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenu jMenuBack;
    private javax.swing.JMenuBar jMenuBarAbout;
    private javax.swing.JLabel lbl_Vision;
    private javax.swing.JLabel lbl_mission;
    private javax.swing.JLabel lbl_wallpaper;
    // End of variables declaration//GEN-END:variables
}
