/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package View;

import javax.swing.JOptionPane;
import Controller.*;
import Model.Validation;


public class V_Admin_SignUp_Page extends javax.swing.JFrame {

 
    public V_Admin_SignUp_Page() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lbl_PersonalDetails = new javax.swing.JLabel();
        lbl_Registration = new javax.swing.JLabel();
        lbl_AccountAuthenification = new javax.swing.JLabel();
        lbl_Email = new javax.swing.JLabel();
        lbl_Password = new javax.swing.JLabel();
        lbl_ConfirmPassword = new javax.swing.JLabel();
        txt_Email = new javax.swing.JTextField();
        txt_Password = new javax.swing.JTextField();
        txt_ConfirmPassword = new javax.swing.JTextField();
        lbl_NIC = new javax.swing.JLabel();
        lbl_Name = new javax.swing.JLabel();
        lbl_Department = new javax.swing.JLabel();
        lbl_linkedBranch = new javax.swing.JLabel();
        txt_NIC = new javax.swing.JTextField();
        txt_Name = new javax.swing.JTextField();
        txt_Department = new javax.swing.JTextField();
        txt_LinkedBranch = new javax.swing.JTextField();
        lbl_Footer = new javax.swing.JLabel();
        lbl_ContactNo = new javax.swing.JLabel();
        lbl_Address = new javax.swing.JLabel();
        txt_ContactNO = new javax.swing.JTextField();
        lbl_professionaldetails = new javax.swing.JLabel();
        lbl_EmployeeID = new javax.swing.JLabel();
        txt_EmployeeId = new javax.swing.JTextField();
        lbl_Terms = new javax.swing.JLabel();
        btn_Register = new javax.swing.JButton();
        CheckBoxTerms = new javax.swing.JCheckBox();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtA_Address = new javax.swing.JTextArea();
        lbl_Background = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1400, 750));
        setResizable(false);
        setSize(new java.awt.Dimension(1400, 750));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lbl_PersonalDetails.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        lbl_PersonalDetails.setText("Personal Details");
        getContentPane().add(lbl_PersonalDetails, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 70, 205, -1));

        lbl_Registration.setBackground(new java.awt.Color(255, 255, 255));
        lbl_Registration.setFont(new java.awt.Font("Goudy Old Style", 1, 55)); // NOI18N
        lbl_Registration.setText("Registration");
        getContentPane().add(lbl_Registration, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 10, 258, 56));

        lbl_AccountAuthenification.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        lbl_AccountAuthenification.setText("Account Authentication");
        getContentPane().add(lbl_AccountAuthenification, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 70, 280, -1));

        lbl_Email.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lbl_Email.setText("Email");
        getContentPane().add(lbl_Email, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 120, 80, -1));

        lbl_Password.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lbl_Password.setText("Password");
        getContentPane().add(lbl_Password, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 230, 100, -1));

        lbl_ConfirmPassword.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lbl_ConfirmPassword.setText("Confirm Password");
        getContentPane().add(lbl_ConfirmPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 330, 140, -1));

        txt_Email.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        getContentPane().add(txt_Email, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 160, 480, 40));

        txt_Password.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        getContentPane().add(txt_Password, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 260, 480, 40));

        txt_ConfirmPassword.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        getContentPane().add(txt_ConfirmPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 360, 480, 40));

        lbl_NIC.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lbl_NIC.setText("NIC Number");
        getContentPane().add(lbl_NIC, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 140, 90, -1));

        lbl_Name.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lbl_Name.setText("Name");
        getContentPane().add(lbl_Name, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 200, 70, -1));

        lbl_Department.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lbl_Department.setText("Department");
        getContentPane().add(lbl_Department, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 460, 110, -1));

        lbl_linkedBranch.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lbl_linkedBranch.setText("Linked Branch");
        getContentPane().add(lbl_linkedBranch, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 530, 110, 21));

        txt_NIC.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        getContentPane().add(txt_NIC, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 130, 490, 40));

        txt_Name.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        getContentPane().add(txt_Name, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 190, 490, 40));

        txt_Department.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        getContentPane().add(txt_Department, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 460, 480, 40));

        txt_LinkedBranch.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        getContentPane().add(txt_LinkedBranch, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 520, 480, 40));

        lbl_Footer.setFont(new java.awt.Font("Goudy Old Style", 1, 18)); // NOI18N
        lbl_Footer.setText("National Blood Bank  @National Blood Transfusion Service");
        getContentPane().add(lbl_Footer, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 680, 440, -1));

        lbl_ContactNo.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lbl_ContactNo.setText("Contact No");
        getContentPane().add(lbl_ContactNo, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 260, 90, -1));

        lbl_Address.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lbl_Address.setText("Address");
        getContentPane().add(lbl_Address, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 320, 80, -1));

        txt_ContactNO.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        getContentPane().add(txt_ContactNO, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 250, 490, 40));

        lbl_professionaldetails.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        lbl_professionaldetails.setText("Professional Details");
        getContentPane().add(lbl_professionaldetails, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 410, 270, -1));

        lbl_EmployeeID.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lbl_EmployeeID.setText("Employee ID");
        getContentPane().add(lbl_EmployeeID, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 590, 100, -1));

        txt_EmployeeId.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        getContentPane().add(txt_EmployeeId, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 580, 480, 40));

        lbl_Terms.setFont(new java.awt.Font("Segoe Script", 1, 18)); // NOI18N
        lbl_Terms.setForeground(new java.awt.Color(255, 255, 255));
        lbl_Terms.setText("Terms and Conditions");
        lbl_Terms.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbl_TermsMouseClicked(evt);
            }
        });
        getContentPane().add(lbl_Terms, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 480, 250, -1));

        btn_Register.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        btn_Register.setText("REGISTER");
        btn_Register.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_RegisterActionPerformed(evt);
            }
        });
        getContentPane().add(btn_Register, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 540, 200, 60));

        CheckBoxTerms.setBackground(new java.awt.Color(255, 255, 255));
        CheckBoxTerms.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        CheckBoxTerms.setText("I Agreed to Terms and Conditions.");
        getContentPane().add(CheckBoxTerms, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 430, 320, -1));

        txtA_Address.setColumns(20);
        txtA_Address.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        txtA_Address.setRows(5);
        jScrollPane1.setViewportView(txtA_Address);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 310, 490, 70));

        lbl_Background.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/adminsignup.jpg"))); // NOI18N
        getContentPane().add(lbl_Background, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1400, -1));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btn_RegisterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_RegisterActionPerformed
       
        try
        {
        boolean value,evalid;
        int Contact_No;
        String NIC,Name,Address,Department,Linked_Branch,EmployeeID,Email,Password,Confirm_Password;
        NIC=txt_NIC.getText();
        Name=txt_Name.getText();
        Contact_No=Integer.parseInt(txt_ContactNO.getText());
        Address=txtA_Address.getText();
        Department=txt_Department.getText();
        Linked_Branch=txt_LinkedBranch.getText();
        EmployeeID=txt_EmployeeId.getText();
        Email=txt_Email.getText();
        Password=txt_Password.getText();
        Confirm_Password=txt_ConfirmPassword.getText();
         Validation v=new Validation();
        evalid= Validation.EmailValidation(Email);
        if(evalid==true)
        {
            if(Password.equals(Confirm_Password))
              {
                     if(this.CheckBoxTerms.isSelected())
                     {
                       //CAdminRegistration c1=new C_Admin_Registration();
                       value=C_Admin_Registration.AdminRegistration(NIC,Name,Contact_No,Address,Department,Linked_Branch,EmployeeID,Email,Password);
                         if(value==true)
                           {
                             
                            V_Admin_logIn_page h1=new V_Admin_logIn_page();
                            h1.setVisible(true);
                            this.setVisible(false);
                           }
                           else
                           {
                            JOptionPane.showMessageDialog(null, "Please try again shortly !!!");
                           }
                     }
                     else
                     {
                         JOptionPane.showMessageDialog(null,"Please Agree to Terms and Conditions");
                     } 
              }
              else
              {
                   JOptionPane.showMessageDialog(null,"Please Enter Password Correctly Again");
              }
        }
        else
        {
            JOptionPane.showMessageDialog(null, "Please enter valid email");
        }
        
        }
        catch(Exception ex)
        {
            JOptionPane.showMessageDialog(null, ex);
        }
       
        
        
    }//GEN-LAST:event_btn_RegisterActionPerformed

    private void lbl_TermsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_TermsMouseClicked
        // TODO add your handling code here:
        V_TermsAndConditions ts=new V_TermsAndConditions();
        ts.setVisible(true);
    }//GEN-LAST:event_lbl_TermsMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(V_Admin_SignUp_Page.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(V_Admin_SignUp_Page.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(V_Admin_SignUp_Page.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(V_Admin_SignUp_Page.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new V_Admin_SignUp_Page().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox CheckBoxTerms;
    private javax.swing.JButton btn_Register;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lbl_AccountAuthenification;
    private javax.swing.JLabel lbl_Address;
    private javax.swing.JLabel lbl_Background;
    private javax.swing.JLabel lbl_ConfirmPassword;
    private javax.swing.JLabel lbl_ContactNo;
    private javax.swing.JLabel lbl_Department;
    private javax.swing.JLabel lbl_Email;
    private javax.swing.JLabel lbl_EmployeeID;
    private javax.swing.JLabel lbl_Footer;
    private javax.swing.JLabel lbl_NIC;
    private javax.swing.JLabel lbl_Name;
    private javax.swing.JLabel lbl_Password;
    private javax.swing.JLabel lbl_PersonalDetails;
    private javax.swing.JLabel lbl_Registration;
    private javax.swing.JLabel lbl_Terms;
    private javax.swing.JLabel lbl_linkedBranch;
    private javax.swing.JLabel lbl_professionaldetails;
    private javax.swing.JTextArea txtA_Address;
    private javax.swing.JTextField txt_ConfirmPassword;
    private javax.swing.JTextField txt_ContactNO;
    private javax.swing.JTextField txt_Department;
    private javax.swing.JTextField txt_Email;
    private javax.swing.JTextField txt_EmployeeId;
    private javax.swing.JTextField txt_LinkedBranch;
    private javax.swing.JTextField txt_NIC;
    private javax.swing.JTextField txt_Name;
    private javax.swing.JTextField txt_Password;
    // End of variables declaration//GEN-END:variables
}
