/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package View;

import java.awt.Desktop;
import java.io.IOException;
import java.net.URI;
import java.net.URISyntaxException;
import javax.swing.JOptionPane;

/**
 * @author Yasiru
 * contact me : https://linktr.ee/yasiruchamuditha for more information.
 */
public class V_ContactUs extends javax.swing.JFrame {

    /**
     * Creates new form V_ContactUs
     */
    public V_ContactUs() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panel_body = new javax.swing.JPanel();
        lbl_Tele = new javax.swing.JLabel();
        lbl_web = new javax.swing.JLabel();
        lblWeb = new javax.swing.JLabel();
        lbl_Headline = new javax.swing.JLabel();
        lbl_logo = new javax.swing.JLabel();
        jMenuBarContactUs = new javax.swing.JMenuBar();
        jMenuBack = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(1000, 700));
        setMinimumSize(new java.awt.Dimension(1000, 700));
        setPreferredSize(new java.awt.Dimension(1000, 700));
        setResizable(false);
        setSize(new java.awt.Dimension(1000, 700));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panel_body.setBackground(new java.awt.Color(255, 204, 204));
        panel_body.setForeground(new java.awt.Color(153, 255, 153));
        panel_body.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lbl_Tele.setFont(new java.awt.Font("Segoe UI", 1, 26)); // NOI18N
        lbl_Tele.setText("<html>\n<p>\nNational Blood Center\nNo.555/5D, Elvitigala Mawatha, Colombo 05, Sri Lanka.<br>\n\nTel : +94 112 369 931 Ext : 203 / 297<br>\nFax : +94 112 369 937 / +94 112 369 939<br>\n\nEmail : info@nbts.health.gov.lk<br>\n</p>\n</html>");
        panel_body.add(lbl_Tele, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 60, 510, 240));

        lbl_web.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        lbl_web.setText("<html>\n<p>\nHead of WHO Collaborating Center : Dr. Lakshman Edirisinghe <br>                                       \nContact : +94 773017340, lakshman.edi@gmail.com\n</p>\n<p>\nMedical Officer In-charge : Dr. Dilani Jayalath<br>\nContact : +94 718 035 811, dilanijayalath@yahoo.com \n</p>\n<p>\nTraining Coordinator – International Training : Dr. Charuni Kohombange<br>\nContact : +94 714 410 467, moplnbts@gmail.com\n</p>\n<p>\nTraining Coordinator – Local Training : Dr. Indika Rupasena<br>\nContact : +94 714 442 361, indikarupasena@gmail.com \n</p>\n</html>");
        panel_body.add(lbl_web, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 300, 770, 350));

        lblWeb.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        lblWeb.setForeground(new java.awt.Color(255, 0, 0));
        lblWeb.setText("<html> <p>Web site Click Here !!!<p> </html>");
        lblWeb.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblWebMouseClicked(evt);
            }
        });
        panel_body.add(lblWeb, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 120, 380, 80));

        lbl_Headline.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        lbl_Headline.setText("<html><h1>National Blood Bank  - Contact Us</h1> </html>");
        panel_body.add(lbl_Headline, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 10, 410, 40));

        lbl_logo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/Logo_size_1.png"))); // NOI18N
        panel_body.add(lbl_logo, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 400, 260, 230));

        getContentPane().add(panel_body, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1000, 660));

        jMenuBack.setText("Back");
        jMenuBack.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jMenuBack.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenuBackMouseClicked(evt);
            }
        });
        jMenuBarContactUs.add(jMenuBack);

        setJMenuBar(jMenuBarContactUs);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuBackMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenuBackMouseClicked
        // TODO add your handling code here:
        V_Home_page hp=new V_Home_page();
        hp.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jMenuBackMouseClicked

    private void lblWebMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblWebMouseClicked
        // TODO add your handling code here:
         Desktop browser=Desktop.getDesktop();
        try
        {
            browser.browse(new URI("http://nbts.health.gov.lk/"));
        }
        catch(IOException | URISyntaxException er)
        {
            JOptionPane.showMessageDialog(null, er);
        }
        
    }//GEN-LAST:event_lblWebMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(V_ContactUs.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(V_ContactUs.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(V_ContactUs.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(V_ContactUs.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new V_ContactUs().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu jMenuBack;
    private javax.swing.JMenuBar jMenuBarContactUs;
    private javax.swing.JLabel lblWeb;
    private javax.swing.JLabel lbl_Headline;
    private javax.swing.JLabel lbl_Tele;
    private javax.swing.JLabel lbl_logo;
    private javax.swing.JLabel lbl_web;
    private javax.swing.JPanel panel_body;
    // End of variables declaration//GEN-END:variables
}
