/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package View;

/**
 * @author Yasiru
 * contact me : https://linktr.ee/yasiruchamuditha for more information.
 */
public class V_Details_of_Blood extends javax.swing.JFrame {

    /**
     * Creates new form V_Details_of_Blood
     */
    public V_Details_of_Blood() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelbody = new javax.swing.JPanel();
        lbl_wallpaper = new javax.swing.JLabel();
        jMenuBardetailsofBlood = new javax.swing.JMenuBar();
        jMenuback = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(1000, 700));
        setMinimumSize(new java.awt.Dimension(1000, 700));
        setPreferredSize(new java.awt.Dimension(1000, 700));
        setResizable(false);
        setSize(new java.awt.Dimension(1000, 700));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panelbody.setBackground(new java.awt.Color(255, 255, 102));
        panelbody.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lbl_wallpaper.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        lbl_wallpaper.setText("<html> <h1><center><font color=red>ABOUT BLOOD</font></center></h1> <p> The ABO blood group system was discovered by Karl Landsteiner in 1900. 46 years later (1946) the Blood Transfusion Service was formed. In 1950 the National Blood Service was formed to collect and provide blood supplies for all the hospitals in Sri Lanka.  Blood comes in four main types - O, A, B and AB. Group O is the most common which means it is in high demand. Blood can also be subdivided into its main components - red cells, white cells, platelets and plasma. Unfortunately red cells only have a shelf-life of 35 or 42 days, while platelets shelf life is even less, only five days.  Almost anyone between the ages of 18 and 55 can become a new blood donor. And those who are regular donors can continue to donate till 60.  The average adult has around 5 trillion red blood cells in one litre of blood. Which means you have on average 25 trillion red cells running around inside you, although 25 million (or 0.1%) of them die every day. That works out at roughly 300 a second.  William Harvey was the first physician to discover that blood circulates round the body back in 1628. Sir Christopher Wren (St Paul's Cathedral Christopher Wren) actually injected fluids into the circulation of animals, using an instrument invented by the aforementioned Mr Harvey.  The first successful blood transfusion was carried out in 1665 by Dr Richard Lower. He used dogs as the donor and recipient. However, when they started performing transfusions on humans, they couldn't understand why the people receiving the blood kept dying. It wasn't until 1900 that Dr Karl Landsteiner discovered the ABO blood group system and realised that human patients needed to be given compatible blood. He got the Nobel Prize for his discovery.</p> </html>");
        panelbody.add(lbl_wallpaper, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 970, 640));

        getContentPane().add(panelbody, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1000, 660));

        jMenuback.setText("  Back  ");
        jMenuback.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jMenuback.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenubackMouseClicked(evt);
            }
        });
        jMenuBardetailsofBlood.add(jMenuback);

        setJMenuBar(jMenuBardetailsofBlood);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jMenubackMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenubackMouseClicked
        // TODO add your handling code here:
        V_Home_page hp=new V_Home_page();
        hp.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jMenubackMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(V_Details_of_Blood.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(V_Details_of_Blood.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(V_Details_of_Blood.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(V_Details_of_Blood.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new V_Details_of_Blood().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuBar jMenuBardetailsofBlood;
    private javax.swing.JMenu jMenuback;
    private javax.swing.JLabel lbl_wallpaper;
    private javax.swing.JPanel panelbody;
    // End of variables declaration//GEN-END:variables
}
