/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package View;

import Controller.*;
import Model.SelectedUser;
import javax.swing.JOptionPane;

/**
 * @author Yasiru
 * contact me : https://linktr.ee/yasiruchamuditha for more information.
 */
public class V_Donor_login_page extends javax.swing.JFrame {

    /**
     * Creates new form V_Donor_login_page
     */
    public V_Donor_login_page() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lbl_headline1 = new javax.swing.JLabel();
        lbl_Logo = new javax.swing.JLabel();
        lbl_headline2 = new javax.swing.JLabel();
        lbl_Login = new javax.swing.JLabel();
        lbl_NIC = new javax.swing.JLabel();
        lbl_Password = new javax.swing.JLabel();
        lbl_Footer1 = new javax.swing.JLabel();
        lbl_Footer2 = new javax.swing.JLabel();
        btn_SignIn = new javax.swing.JButton();
        txt_DNIC = new javax.swing.JTextField();
        lbl_ForgottonPassword = new javax.swing.JLabel();
        lbl_Accountstatus = new javax.swing.JLabel();
        lbl_SignUp = new javax.swing.JLabel();
        pf_Dpassword = new javax.swing.JPasswordField();
        lbl_wallpaper = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(1000, 700));
        setMinimumSize(new java.awt.Dimension(1000, 700));
        setResizable(false);
        setSize(new java.awt.Dimension(1000, 700));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lbl_headline1.setFont(new java.awt.Font("Pristina", 1, 65)); // NOI18N
        lbl_headline1.setText("DONATE BLOOD");
        getContentPane().add(lbl_headline1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 483, -1));

        lbl_Logo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/Logo_size_3.png"))); // NOI18N
        getContentPane().add(lbl_Logo, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 10, 50, 50));

        lbl_headline2.setFont(new java.awt.Font("Viner Hand ITC", 1, 65)); // NOI18N
        lbl_headline2.setText("SAVE LIFE");
        getContentPane().add(lbl_headline2, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 100, 375, 78));

        lbl_Login.setFont(new java.awt.Font("Segoe UI", 1, 60)); // NOI18N
        lbl_Login.setText("LOG IN");
        getContentPane().add(lbl_Login, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 70, 210, -1));

        lbl_NIC.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/usernameicon.png"))); // NOI18N
        getContentPane().add(lbl_NIC, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 230, 50, -1));

        lbl_Password.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/passwordicon.png"))); // NOI18N
        getContentPane().add(lbl_Password, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 330, 60, 70));

        lbl_Footer1.setFont(new java.awt.Font("Goudy Old Style", 1, 48)); // NOI18N
        lbl_Footer1.setText("National Blood Bank");
        getContentPane().add(lbl_Footer1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 550, 404, -1));

        lbl_Footer2.setFont(new java.awt.Font("Gabriola", 1, 36)); // NOI18N
        lbl_Footer2.setText("@National Blood Transfusion Service");
        getContentPane().add(lbl_Footer2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 610, 460, -1));

        btn_SignIn.setFont(new java.awt.Font("Segoe UI", 1, 48)); // NOI18N
        btn_SignIn.setText("SIGN IN");
        btn_SignIn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_SignInActionPerformed(evt);
            }
        });
        getContentPane().add(btn_SignIn, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 450, 230, -1));

        txt_DNIC.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        getContentPane().add(txt_DNIC, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 230, 330, 50));

        lbl_ForgottonPassword.setFont(new java.awt.Font("Segoe Script", 1, 24)); // NOI18N
        lbl_ForgottonPassword.setText("Forgotton Password ?");
        lbl_ForgottonPassword.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbl_ForgottonPasswordMouseClicked(evt);
            }
        });
        getContentPane().add(lbl_ForgottonPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 540, 290, -1));

        lbl_Accountstatus.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lbl_Accountstatus.setText("Don't have an Account ?");
        getContentPane().add(lbl_Accountstatus, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 590, 190, -1));

        lbl_SignUp.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        lbl_SignUp.setText("SIGN UP ");
        lbl_SignUp.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbl_SignUpMouseClicked(evt);
            }
        });
        getContentPane().add(lbl_SignUp, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 620, 160, -1));

        pf_Dpassword.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        getContentPane().add(pf_Dpassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 340, 330, 50));

        lbl_wallpaper.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/Donor_Login_Wallpaper.png"))); // NOI18N
        getContentPane().add(lbl_wallpaper, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1000, 700));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btn_SignInActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_SignInActionPerformed
        // TODO add your handling code here:
        String NIC,Password;
        boolean value;
        NIC=txt_DNIC.getText();
        Password=pf_Dpassword.getText();
        SelectedUser su=new SelectedUser();
        su.selectAuthenification(NIC,Password);
        //CDonorLogin c1=new C_Donor_Login();
        value=C_Donor_Login.DonorLogin(NIC, Password);
        if(value==true)
        {
            V_Home_page h1=new V_Home_page();
            h1.setVisible(true);
            this.setVisible(false);
        }
        else
        {
            JOptionPane.showMessageDialog(null, "Please Try Again Shortly!!!!");
        }
        
        
    }//GEN-LAST:event_btn_SignInActionPerformed

    private void lbl_SignUpMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_SignUpMouseClicked
        // TODO add your handling code here:
        V_Donor_signUp_page ds=new V_Donor_signUp_page();
        ds.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_lbl_SignUpMouseClicked

    private void lbl_ForgottonPasswordMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_ForgottonPasswordMouseClicked
        // TODO add your handling code here:
        VerificationPage v=new VerificationPage();
        v.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_lbl_ForgottonPasswordMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(V_Donor_login_page.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(V_Donor_login_page.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(V_Donor_login_page.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(V_Donor_login_page.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new V_Donor_login_page().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_SignIn;
    private javax.swing.JLabel lbl_Accountstatus;
    private javax.swing.JLabel lbl_Footer1;
    private javax.swing.JLabel lbl_Footer2;
    private javax.swing.JLabel lbl_ForgottonPassword;
    private javax.swing.JLabel lbl_Login;
    private javax.swing.JLabel lbl_Logo;
    private javax.swing.JLabel lbl_NIC;
    private javax.swing.JLabel lbl_Password;
    private javax.swing.JLabel lbl_SignUp;
    private javax.swing.JLabel lbl_headline1;
    private javax.swing.JLabel lbl_headline2;
    private javax.swing.JLabel lbl_wallpaper;
    private javax.swing.JPasswordField pf_Dpassword;
    private javax.swing.JTextField txt_DNIC;
    // End of variables declaration//GEN-END:variables
}
