/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package View;

import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.Date;
import Controller.*;
import javax.swing.JOptionPane;

/**
 *
 * @author Yasiru
 */
public class V_Donation extends javax.swing.JFrame {

    /**
     * Creates new form V_Donation
     */
    public V_Donation() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lbl_Headline = new javax.swing.JLabel();
        lbl_DonorId = new javax.swing.JLabel();
        lbl_Name = new javax.swing.JLabel();
        lbl_Date = new javax.swing.JLabel();
        lbl_Time = new javax.swing.JLabel();
        lbl_BloodGroup = new javax.swing.JLabel();
        lbl_BodyWeight = new javax.swing.JLabel();
        lbl_BloodGloucoseLevel = new javax.swing.JLabel();
        lbl_BloodPressure = new javax.swing.JLabel();
        lbl_Temperature = new javax.swing.JLabel();
        lbl_DonatedPlace = new javax.swing.JLabel();
        lbl_footer = new javax.swing.JLabel();
        lbl_Logo = new javax.swing.JLabel();
        txt_DonorID = new javax.swing.JTextField();
        txt_DonorName = new javax.swing.JTextField();
        DatePickerDate = new org.jdesktop.swingx.JXDatePicker();
        txt_Time = new javax.swing.JTextField();
        txt_BodyWeight = new javax.swing.JTextField();
        txt_BloodGloucoseLevel = new javax.swing.JTextField();
        txt_BloodPressure = new javax.swing.JTextField();
        txt_BodyTemperature = new javax.swing.JTextField();
        txt_DonatedPlace = new javax.swing.JTextField();
        txt_InchargeOfficerID = new javax.swing.JTextField();
        btn_Submit = new javax.swing.JButton();
        cmb_BloodGroup = new javax.swing.JComboBox<>();
        lbl_NoOfBags = new javax.swing.JLabel();
        txt_NoOfBags = new javax.swing.JTextField();
        lbl_WeightOfBlood = new javax.swing.JLabel();
        txt_WeightOfBlood = new javax.swing.JTextField();
        lbl_OfficerInchargeID = new javax.swing.JLabel();
        lbl_back = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(1400, 750));
        setMinimumSize(new java.awt.Dimension(1400, 750));
        setResizable(false);
        setSize(new java.awt.Dimension(1400, 750));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lbl_Headline.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        lbl_Headline.setText("Blood Donation Registration");
        getContentPane().add(lbl_Headline, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 10, -1, -1));

        lbl_DonorId.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lbl_DonorId.setText("Donor NIC");
        getContentPane().add(lbl_DonorId, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 90, 100, 20));

        lbl_Name.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lbl_Name.setText("Donor Name");
        getContentPane().add(lbl_Name, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 170, 120, -1));

        lbl_Date.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lbl_Date.setText("Date");
        getContentPane().add(lbl_Date, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 240, 70, -1));

        lbl_Time.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lbl_Time.setText("Time");
        getContentPane().add(lbl_Time, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 310, 70, -1));

        lbl_BloodGroup.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lbl_BloodGroup.setText("Blood Group");
        getContentPane().add(lbl_BloodGroup, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 380, 110, -1));

        lbl_BodyWeight.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lbl_BodyWeight.setText("Body Weight");
        getContentPane().add(lbl_BodyWeight, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 460, 110, -1));

        lbl_BloodGloucoseLevel.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lbl_BloodGloucoseLevel.setText("Blood Glucose Level");
        getContentPane().add(lbl_BloodGloucoseLevel, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 530, 150, -1));

        lbl_BloodPressure.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lbl_BloodPressure.setText("Blood Pressure");
        getContentPane().add(lbl_BloodPressure, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 90, 120, 20));

        lbl_Temperature.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lbl_Temperature.setText("Body Temperature");
        getContentPane().add(lbl_Temperature, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 170, 140, 20));

        lbl_DonatedPlace.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lbl_DonatedPlace.setText("Donated Place");
        getContentPane().add(lbl_DonatedPlace, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 240, 130, 20));

        lbl_footer.setFont(new java.awt.Font("Goudy Old Style", 1, 18)); // NOI18N
        lbl_footer.setText("National Blood Bank @National Blood Transfusion Service");
        getContentPane().add(lbl_footer, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 690, 510, 28));

        lbl_Logo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/Logo_size_3.png"))); // NOI18N
        getContentPane().add(lbl_Logo, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 680, 50, 50));

        txt_DonorID.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        getContentPane().add(txt_DonorID, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 80, 360, 40));

        txt_DonorName.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        getContentPane().add(txt_DonorName, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 160, 360, 40));
        getContentPane().add(DatePickerDate, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 230, 360, 40));

        txt_Time.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        getContentPane().add(txt_Time, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 300, 360, 40));

        txt_BodyWeight.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        getContentPane().add(txt_BodyWeight, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 450, 360, 40));

        txt_BloodGloucoseLevel.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        getContentPane().add(txt_BloodGloucoseLevel, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 520, 360, 40));

        txt_BloodPressure.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        getContentPane().add(txt_BloodPressure, new org.netbeans.lib.awtextra.AbsoluteConstraints(950, 80, 350, 40));

        txt_BodyTemperature.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        getContentPane().add(txt_BodyTemperature, new org.netbeans.lib.awtextra.AbsoluteConstraints(950, 160, 350, 40));

        txt_DonatedPlace.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        getContentPane().add(txt_DonatedPlace, new org.netbeans.lib.awtextra.AbsoluteConstraints(950, 230, 350, 40));

        txt_InchargeOfficerID.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        getContentPane().add(txt_InchargeOfficerID, new org.netbeans.lib.awtextra.AbsoluteConstraints(950, 460, 350, 40));

        btn_Submit.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        btn_Submit.setText("SUBMIT");
        btn_Submit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_SubmitActionPerformed(evt);
            }
        });
        getContentPane().add(btn_Submit, new org.netbeans.lib.awtextra.AbsoluteConstraints(960, 570, 330, -1));

        cmb_BloodGroup.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        cmb_BloodGroup.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Please Select", "A+", "A-", "B+", "B-", "AB+", "AB-", "O+", "O-", " " }));
        getContentPane().add(cmb_BloodGroup, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 370, 360, 40));

        lbl_NoOfBags.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lbl_NoOfBags.setText("No Of Bags");
        getContentPane().add(lbl_NoOfBags, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 310, 110, -1));

        txt_NoOfBags.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        getContentPane().add(txt_NoOfBags, new org.netbeans.lib.awtextra.AbsoluteConstraints(950, 300, 350, 40));

        lbl_WeightOfBlood.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lbl_WeightOfBlood.setText("Weight Of Blood ");
        getContentPane().add(lbl_WeightOfBlood, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 390, 120, -1));

        txt_WeightOfBlood.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        getContentPane().add(txt_WeightOfBlood, new org.netbeans.lib.awtextra.AbsoluteConstraints(950, 380, 350, 40));

        lbl_OfficerInchargeID.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lbl_OfficerInchargeID.setText("Incharge Officer ID");
        getContentPane().add(lbl_OfficerInchargeID, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 470, 170, -1));

        lbl_back.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        lbl_back.setText("Back");
        lbl_back.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbl_backMouseClicked(evt);
            }
        });
        getContentPane().add(lbl_back, new org.netbeans.lib.awtextra.AbsoluteConstraints(1298, 686, 100, 60));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btn_SubmitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_SubmitActionPerformed
        // TODO add your handling code here:
        int No_Of_Bags;
        boolean value,stock;
        String Donor_NIC,Donor_Name,Date,Time,Blood_Group,Body_Weight,Blood_Glucose_Level, Blood_Pressure,Body_Temperature,Donated_Place,Weight_Of_Bags,Incharge_Officer_Id ;
        Donor_NIC=txt_DonorID.getText();
        Donor_Name=txt_DonorName.getText();
         //create object in adte class and get value feon date picker
        Date Date1=DatePickerDate.getDate();
        //create object in date format class and call SimpleDateFormat method
        DateFormat dformat=new SimpleDateFormat("yyyy-MM-dd");
        //assign formated date to dob variable
        Date=dformat.format(Date1);
        Time=txt_Time.getText();
        Blood_Group=cmb_BloodGroup.getSelectedItem().toString(); 
        Body_Weight=txt_BodyWeight.getText();
        Blood_Glucose_Level=txt_BloodGloucoseLevel.getText();
        Blood_Pressure=txt_BloodPressure.getText();
        Body_Temperature=txt_BloodPressure.getText();
        Donated_Place=txt_DonatedPlace.getText();
        No_Of_Bags=Integer.parseInt(txt_NoOfBags.getText());
        Weight_Of_Bags=txt_WeightOfBlood.getText();
        Incharge_Officer_Id=txt_InchargeOfficerID.getText();
        //C_Donation cd=new C_Donation();
        value=C_Donation.Donation(Donor_NIC, Donor_Name, Date, Time, Blood_Group, Body_Weight, Blood_Glucose_Level, Blood_Pressure, Body_Temperature, Donated_Place, No_Of_Bags, Weight_Of_Bags, Incharge_Officer_Id);
        stock=C_Donation.updateStockDonation(No_Of_Bags,Blood_Group);
        if(value==true) 
        {
            if(stock==true)
            {
                JOptionPane.showMessageDialog(null,"Donation Succesfully Registered ");
                txt_DonorID.setText(null);
                txt_DonorName.setText(null);
                txt_Time.setText(null);
                cmb_BloodGroup.setSelectedIndex(0);
                txt_BodyWeight.setText(null);
                txt_BloodGloucoseLevel.setText(null);
                txt_BloodPressure.setText(null);
                txt_BodyTemperature.setText(null);
                txt_DonatedPlace.setText(null);
                txt_NoOfBags.setText(null);
                txt_WeightOfBlood.setText(null);
                txt_InchargeOfficerID.setText(null);
            }
            else
            {
                JOptionPane.showMessageDialog(null,"Storage is not updated,Please Immediately Contact Admin panel for Responce");
            }
               
        }
        else
        {
             JOptionPane.showMessageDialog(null,"Please Try Again shortly");
        }    
    }//GEN-LAST:event_btn_SubmitActionPerformed

    private void lbl_backMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_backMouseClicked
        // TODO add your handling code here:
        V_home_admin ad=new V_home_admin();
        ad.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_lbl_backMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(V_Donation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(V_Donation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(V_Donation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(V_Donation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new V_Donation().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private org.jdesktop.swingx.JXDatePicker DatePickerDate;
    private javax.swing.JButton btn_Submit;
    private javax.swing.JComboBox<String> cmb_BloodGroup;
    private javax.swing.JLabel lbl_BloodGloucoseLevel;
    private javax.swing.JLabel lbl_BloodGroup;
    private javax.swing.JLabel lbl_BloodPressure;
    private javax.swing.JLabel lbl_BodyWeight;
    private javax.swing.JLabel lbl_Date;
    private javax.swing.JLabel lbl_DonatedPlace;
    private javax.swing.JLabel lbl_DonorId;
    private javax.swing.JLabel lbl_Headline;
    private javax.swing.JLabel lbl_Logo;
    private javax.swing.JLabel lbl_Name;
    private javax.swing.JLabel lbl_NoOfBags;
    private javax.swing.JLabel lbl_OfficerInchargeID;
    private javax.swing.JLabel lbl_Temperature;
    private javax.swing.JLabel lbl_Time;
    private javax.swing.JLabel lbl_WeightOfBlood;
    private javax.swing.JLabel lbl_back;
    private javax.swing.JLabel lbl_footer;
    private javax.swing.JTextField txt_BloodGloucoseLevel;
    private javax.swing.JTextField txt_BloodPressure;
    private javax.swing.JTextField txt_BodyTemperature;
    private javax.swing.JTextField txt_BodyWeight;
    private javax.swing.JTextField txt_DonatedPlace;
    private javax.swing.JTextField txt_DonorID;
    private javax.swing.JTextField txt_DonorName;
    private javax.swing.JTextField txt_InchargeOfficerID;
    private javax.swing.JTextField txt_NoOfBags;
    private javax.swing.JTextField txt_Time;
    private javax.swing.JTextField txt_WeightOfBlood;
    // End of variables declaration//GEN-END:variables
}
