/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package View;

import javax.swing.JOptionPane;

/**
 * @author Yasiru
 * contact me : https://linktr.ee/yasiruchamuditha for more information.
 */
public class V_FirstView_Page extends javax.swing.JFrame {

    /**
     * Creates new form FirstView
     */
    public V_FirstView_Page() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panel_background = new javax.swing.JPanel();
        lbl_loading = new javax.swing.JLabel();
        lbl_secondHeading = new javax.swing.JLabel();
        lbl_loadingvalue = new javax.swing.JLabel();
        lbl_Headline = new javax.swing.JLabel();
        jProgressBar_Firstview = new javax.swing.JProgressBar();
        lbl_wallpaperfirstview = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setMinimumSize(new java.awt.Dimension(1000, 700));
        setUndecorated(true);
        setResizable(false);
        setSize(new java.awt.Dimension(1000, 700));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panel_background.setBackground(new java.awt.Color(255, 255, 255));
        panel_background.setPreferredSize(new java.awt.Dimension(1000, 700));
        panel_background.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lbl_loading.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        lbl_loading.setForeground(new java.awt.Color(255, 255, 255));
        lbl_loading.setText("Loading......");
        panel_background.add(lbl_loading, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 630, 440, -1));

        lbl_secondHeading.setFont(new java.awt.Font("Segoe UI", 1, 30)); // NOI18N
        lbl_secondHeading.setForeground(new java.awt.Color(255, 255, 255));
        lbl_secondHeading.setText("@National Blood Transfusion Service");
        panel_background.add(lbl_secondHeading, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 50, 640, 50));

        lbl_loadingvalue.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        lbl_loadingvalue.setForeground(new java.awt.Color(255, 255, 255));
        lbl_loadingvalue.setText("0%");
        panel_background.add(lbl_loadingvalue, new org.netbeans.lib.awtextra.AbsoluteConstraints(910, 630, 80, -1));

        lbl_Headline.setFont(new java.awt.Font("Segoe UI", 1, 52)); // NOI18N
        lbl_Headline.setForeground(new java.awt.Color(255, 255, 255));
        lbl_Headline.setText("National Blood Bank");
        panel_background.add(lbl_Headline, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 0, 560, -1));
        panel_background.add(jProgressBar_Firstview, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 670, 1000, 30));

        lbl_wallpaperfirstview.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/Firstview_wallpaper.jpg"))); // NOI18N
        lbl_wallpaperfirstview.setText("jLabel5");
        panel_background.add(lbl_wallpaperfirstview, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1000, -1));

        getContentPane().add(panel_background, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 700));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(V_FirstView_Page.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(V_FirstView_Page.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(V_FirstView_Page.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(V_FirstView_Page.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
       /* java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new V_FirstView_Page().setVisible(true);
            }
        }); */
       V_FirstView_Page fv=new V_FirstView_Page();
       fv.setVisible(true);
       try
       {
           for(int i=0;i<=100;i++)
           {
               Thread.sleep(100);
               fv.lbl_loadingvalue.setText(i+"%");
               if(i==10)
                {
                    fv.lbl_loading.setText("Turning On Modules......");
                }
                if(i==20)
                {
                      fv.lbl_loading.setText("Loading Modules......");
                }
                if(i==50)
                {
                      fv.lbl_loading.setText("Connecting To Databases......");
                }
                if(i==70)
                {
                      fv.lbl_loading.setText("Connection Succesfully......");
                }
                if(i==85)
                {
                      fv.lbl_loading.setText("Launching Application......");
                }
                fv.jProgressBar_Firstview.setValue(i);   
           }
            fv.setVisible(false);
            V_MainLogin_window M1=new V_MainLogin_window();
            M1.setVisible(true);
       }
       catch(Exception ex)
       {
           JOptionPane.showMessageDialog(null, ex.getMessage());
       }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JProgressBar jProgressBar_Firstview;
    private javax.swing.JLabel lbl_Headline;
    private javax.swing.JLabel lbl_loading;
    private javax.swing.JLabel lbl_loadingvalue;
    private javax.swing.JLabel lbl_secondHeading;
    private javax.swing.JLabel lbl_wallpaperfirstview;
    private javax.swing.JPanel panel_background;
    // End of variables declaration//GEN-END:variables
}
