/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package View;

import javax.swing.JOptionPane;
import Controller.*;
import Model.Validation;

/**
 *
 * @author Yasiru
 */
public class V_MedicalStuff_SignUp_Page extends javax.swing.JFrame {

    /**
     * Creates new form MedicalStuff_SignUp_Page
     */
    public V_MedicalStuff_SignUp_Page() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lbl_Registration = new javax.swing.JLabel();
        lbl_PersonalDetails = new javax.swing.JLabel();
        lbl_NIC = new javax.swing.JLabel();
        lbl_Name = new javax.swing.JLabel();
        lbl_linkedBranch = new javax.swing.JLabel();
        lbl_department = new javax.swing.JLabel();
        lbl_Gender = new javax.swing.JLabel();
        lbl_Blood_Group = new javax.swing.JLabel();
        lbl_Address = new javax.swing.JLabel();
        lbl_AccountAuthentification = new javax.swing.JLabel();
        lbl_ConfirmPassword = new javax.swing.JLabel();
        lbl_Password = new javax.swing.JLabel();
        txt_Email = new javax.swing.JTextField();
        txt_Password = new javax.swing.JTextField();
        btn_Register = new javax.swing.JButton();
        lbl_Footer = new javax.swing.JLabel();
        txt_NIC = new javax.swing.JTextField();
        txt_Name = new javax.swing.JTextField();
        txt_Department = new javax.swing.JTextField();
        rb_Male = new javax.swing.JRadioButton();
        rb_Female = new javax.swing.JRadioButton();
        cmb_bloodGroup = new javax.swing.JComboBox<>();
        lbl_ContactNO = new javax.swing.JLabel();
        txt_ContactNo = new javax.swing.JTextField();
        lbl_Email = new javax.swing.JLabel();
        txt_ConfirmPassword = new javax.swing.JTextField();
        CheckBoxTerms = new javax.swing.JCheckBox();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtA_Address = new javax.swing.JTextArea();
        lbl_PrefessionalDetails = new javax.swing.JLabel();
        txt_linkedBranch = new javax.swing.JTextField();
        lbl_logo = new javax.swing.JLabel();
        lbl_terms = new javax.swing.JLabel();
        lbl_wallpaper = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1400, 750));
        setSize(new java.awt.Dimension(1400, 750));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lbl_Registration.setFont(new java.awt.Font("Goudy Old Style", 1, 55)); // NOI18N
        lbl_Registration.setText("Registration");
        getContentPane().add(lbl_Registration, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 0, 270, 70));

        lbl_PersonalDetails.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        lbl_PersonalDetails.setText("Personal Details");
        getContentPane().add(lbl_PersonalDetails, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 70, 200, -1));

        lbl_NIC.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lbl_NIC.setText("NIC Number");
        getContentPane().add(lbl_NIC, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 120, 120, -1));

        lbl_Name.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lbl_Name.setText("Name");
        getContentPane().add(lbl_Name, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 180, 70, -1));

        lbl_linkedBranch.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lbl_linkedBranch.setText("Linked Branch");
        getContentPane().add(lbl_linkedBranch, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 570, 110, -1));

        lbl_department.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lbl_department.setText("Department");
        getContentPane().add(lbl_department, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 640, 110, -1));

        lbl_Gender.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lbl_Gender.setText("Gender");
        getContentPane().add(lbl_Gender, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 400, 100, -1));

        lbl_Blood_Group.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lbl_Blood_Group.setText("Blood Group");
        getContentPane().add(lbl_Blood_Group, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 460, 110, -1));

        lbl_Address.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lbl_Address.setText("Address");
        getContentPane().add(lbl_Address, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 330, 100, -1));

        lbl_AccountAuthentification.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        lbl_AccountAuthentification.setText("Account Authentication");
        getContentPane().add(lbl_AccountAuthentification, new org.netbeans.lib.awtextra.AbsoluteConstraints(840, 70, 350, -1));

        lbl_ConfirmPassword.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lbl_ConfirmPassword.setText("Confirm Password");
        getContentPane().add(lbl_ConfirmPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(840, 340, 140, -1));

        lbl_Password.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lbl_Password.setText("Password");
        getContentPane().add(lbl_Password, new org.netbeans.lib.awtextra.AbsoluteConstraints(840, 230, 70, -1));

        txt_Email.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        getContentPane().add(txt_Email, new org.netbeans.lib.awtextra.AbsoluteConstraints(840, 150, 450, 40));

        txt_Password.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        getContentPane().add(txt_Password, new org.netbeans.lib.awtextra.AbsoluteConstraints(840, 270, 450, 40));

        btn_Register.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        btn_Register.setText("REGISTER");
        btn_Register.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_RegisterActionPerformed(evt);
            }
        });
        getContentPane().add(btn_Register, new org.netbeans.lib.awtextra.AbsoluteConstraints(850, 580, 240, 60));

        lbl_Footer.setFont(new java.awt.Font("Goudy Old Style", 1, 18)); // NOI18N
        lbl_Footer.setText("National Blood Bank  @ National Blood Transfusion Service");
        getContentPane().add(lbl_Footer, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 700, 440, -1));

        txt_NIC.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        getContentPane().add(txt_NIC, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 110, 440, 40));

        txt_Name.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        getContentPane().add(txt_Name, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 170, 440, 40));

        txt_Department.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        getContentPane().add(txt_Department, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 630, 440, 40));

        rb_Male.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        rb_Male.setText("Male");
        getContentPane().add(rb_Male, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 400, 140, -1));

        rb_Female.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        rb_Female.setText("Female");
        getContentPane().add(rb_Female, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 400, 150, -1));

        cmb_bloodGroup.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Please Select", "A+", "A-", "B+", "B-", "AB+", "AB-", "O+", "O-" }));
        getContentPane().add(cmb_bloodGroup, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 460, 440, -1));

        lbl_ContactNO.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lbl_ContactNO.setText("Contact No");
        getContentPane().add(lbl_ContactNO, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 260, 110, -1));

        txt_ContactNo.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        getContentPane().add(txt_ContactNo, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 250, 440, 40));

        lbl_Email.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lbl_Email.setText("Email");
        getContentPane().add(lbl_Email, new org.netbeans.lib.awtextra.AbsoluteConstraints(840, 110, 50, -1));

        txt_ConfirmPassword.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        getContentPane().add(txt_ConfirmPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(840, 380, 440, 40));

        CheckBoxTerms.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        CheckBoxTerms.setText("I Agreed to Terms and Conditions.");
        getContentPane().add(CheckBoxTerms, new org.netbeans.lib.awtextra.AbsoluteConstraints(840, 460, -1, -1));

        txtA_Address.setColumns(20);
        txtA_Address.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        txtA_Address.setRows(5);
        jScrollPane1.setViewportView(txtA_Address);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 310, 440, 70));

        lbl_PrefessionalDetails.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        lbl_PrefessionalDetails.setText("Professional Details");
        getContentPane().add(lbl_PrefessionalDetails, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 510, 260, -1));
        getContentPane().add(txt_linkedBranch, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 560, 440, 40));

        lbl_logo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/Logo_size_3.png"))); // NOI18N
        getContentPane().add(lbl_logo, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 680, 50, 60));

        lbl_terms.setFont(new java.awt.Font("Segoe Script", 1, 24)); // NOI18N
        lbl_terms.setText("Terms and Conditions");
        lbl_terms.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbl_termsMouseClicked(evt);
            }
        });
        getContentPane().add(lbl_terms, new org.netbeans.lib.awtextra.AbsoluteConstraints(850, 500, -1, -1));

        lbl_wallpaper.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/Medicalstaff_Signup_wallpaper.png"))); // NOI18N
        getContentPane().add(lbl_wallpaper, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1400, 750));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btn_RegisterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_RegisterActionPerformed
        // TODO add your handling code here:
        try
        {
        boolean value,evalid;
        int Contact_No;
        String NIC,Name,Address,Gender,Blood_Group,Linked_Branch,Department,Email,Password,Confirm_Password;
        NIC=txt_NIC.getText();
        Name=txt_Name.getText();
        Contact_No=Integer.parseInt(txt_ContactNo.getText());
        Address=txtA_Address.getText();
         if(rb_Male.isSelected())
        {
            Gender="M";
        }
        else
        {
            Gender="F";
        }
        Blood_Group=cmb_bloodGroup.getSelectedItem().toString();   
        Linked_Branch=txt_linkedBranch.getText();
        Department=txt_Department.getText();
        Email=txt_Email.getText();
        Password=txt_Password.getText();
        Confirm_Password=txt_ConfirmPassword.getText();
        
         Validation v=new Validation();
        evalid= Validation.EmailValidation(Email);
        
        if(evalid==true)
        {
            if(Password.equals(Confirm_Password))
               {
              if(this.CheckBoxTerms.isSelected())
                 {
                  //C_MedicalStaff_Registration ms=new C_MedicalStaff_Registration();
                  value=C_MedicalStaff_Registration.MedicalStaffRegistration(NIC, Name, Contact_No, Address, Gender, Blood_Group, Linked_Branch,Department, Email, Password);
                    if(value==true)
                           {
                            V_Medical_Staff_login_page h1=new V_Medical_Staff_login_page();
                            h1.setVisible(true);
                            this.setVisible(false);
                           }
                           else
                           {
                            JOptionPane.showMessageDialog(null, "Please try again shortly !!!");
                           }
              }
              else
              {
                   JOptionPane.showMessageDialog(null,"Please Agree to Terms and Conditions");
              }        
         }
         else
         {
             JOptionPane.showMessageDialog(null,"Please Enter Password Correctly Again");
         }
              
        }
        else
        {
              JOptionPane.showMessageDialog(null, "Please enter valid email");
        }
 
                  
        }
        catch(Exception ex)
        {
            JOptionPane.showMessageDialog(null, ex);
        }
    }//GEN-LAST:event_btn_RegisterActionPerformed

    private void lbl_termsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_termsMouseClicked
        // TODO add your handling code here:
        V_TermsAndConditions td=new V_TermsAndConditions();
        td.setVisible(true);
    }//GEN-LAST:event_lbl_termsMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(V_MedicalStuff_SignUp_Page.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(V_MedicalStuff_SignUp_Page.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(V_MedicalStuff_SignUp_Page.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(V_MedicalStuff_SignUp_Page.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new V_MedicalStuff_SignUp_Page().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox CheckBoxTerms;
    private javax.swing.JButton btn_Register;
    private javax.swing.JComboBox<String> cmb_bloodGroup;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lbl_AccountAuthentification;
    private javax.swing.JLabel lbl_Address;
    private javax.swing.JLabel lbl_Blood_Group;
    private javax.swing.JLabel lbl_ConfirmPassword;
    private javax.swing.JLabel lbl_ContactNO;
    private javax.swing.JLabel lbl_Email;
    private javax.swing.JLabel lbl_Footer;
    private javax.swing.JLabel lbl_Gender;
    private javax.swing.JLabel lbl_NIC;
    private javax.swing.JLabel lbl_Name;
    private javax.swing.JLabel lbl_Password;
    private javax.swing.JLabel lbl_PersonalDetails;
    private javax.swing.JLabel lbl_PrefessionalDetails;
    private javax.swing.JLabel lbl_Registration;
    private javax.swing.JLabel lbl_department;
    private javax.swing.JLabel lbl_linkedBranch;
    private javax.swing.JLabel lbl_logo;
    private javax.swing.JLabel lbl_terms;
    private javax.swing.JLabel lbl_wallpaper;
    private javax.swing.JRadioButton rb_Female;
    private javax.swing.JRadioButton rb_Male;
    private javax.swing.JTextArea txtA_Address;
    private javax.swing.JTextField txt_ConfirmPassword;
    private javax.swing.JTextField txt_ContactNo;
    private javax.swing.JTextField txt_Department;
    private javax.swing.JTextField txt_Email;
    private javax.swing.JTextField txt_NIC;
    private javax.swing.JTextField txt_Name;
    private javax.swing.JTextField txt_Password;
    private javax.swing.JTextField txt_linkedBranch;
    // End of variables declaration//GEN-END:variables
}
