/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package View;
import Model.*;
import Controller.*;
import javax.swing.JOptionPane;
/**
 * @author Yasiru
 * contact me : https://linktr.ee/yasiruchamuditha for more information.
 */
public class V_Organization_login extends javax.swing.JFrame {

    /**
     * Creates new form Camp_Organizer_login
     */
    public V_Organization_login() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lbl_Login = new javax.swing.JLabel();
        lbl_DisplayAccountStatus = new javax.swing.JLabel();
        txt_Ousername = new javax.swing.JTextField();
        pf_Opassword = new javax.swing.JPasswordField();
        lbl_username = new javax.swing.JLabel();
        lbl_password = new javax.swing.JLabel();
        btn_SignIn = new javax.swing.JButton();
        lbl_SignIn = new javax.swing.JLabel();
        lbl_Forgotten_password = new javax.swing.JLabel();
        lbl_Footer1 = new javax.swing.JLabel();
        lbl_Footer2 = new javax.swing.JLabel();
        lbl_headline1 = new javax.swing.JLabel();
        lbl_headline2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1000, 700));
        setResizable(false);
        setSize(new java.awt.Dimension(1000, 700));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lbl_Login.setFont(new java.awt.Font("Segoe UI", 1, 60)); // NOI18N
        lbl_Login.setText("LOG IN");
        getContentPane().add(lbl_Login, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 50, -1, -1));

        lbl_DisplayAccountStatus.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lbl_DisplayAccountStatus.setText("Don't Have An Account ?");
        getContentPane().add(lbl_DisplayAccountStatus, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 590, 230, -1));

        txt_Ousername.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        getContentPane().add(txt_Ousername, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 260, 300, 40));

        pf_Opassword.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        getContentPane().add(pf_Opassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 350, 300, 40));

        lbl_username.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/usernameicon.png"))); // NOI18N
        getContentPane().add(lbl_username, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 260, 50, 50));

        lbl_password.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/passwordicon.png"))); // NOI18N
        getContentPane().add(lbl_password, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 340, -1, 60));

        btn_SignIn.setFont(new java.awt.Font("Segoe UI", 1, 48)); // NOI18N
        btn_SignIn.setText("SIGN IN\n");
        btn_SignIn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_SignInActionPerformed(evt);
            }
        });
        getContentPane().add(btn_SignIn, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 470, -1, 60));

        lbl_SignIn.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        lbl_SignIn.setText("SIGN UP\n");
        lbl_SignIn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbl_SignInMouseClicked(evt);
            }
        });
        getContentPane().add(lbl_SignIn, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 620, 150, -1));

        lbl_Forgotten_password.setFont(new java.awt.Font("Segoe Script", 1, 24)); // NOI18N
        lbl_Forgotten_password.setText("Forgotten Password ?");
        lbl_Forgotten_password.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbl_Forgotten_passwordMouseClicked(evt);
            }
        });
        getContentPane().add(lbl_Forgotten_password, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 540, 290, 30));

        lbl_Footer1.setFont(new java.awt.Font("Goudy Old Style", 1, 48)); // NOI18N
        lbl_Footer1.setText("National Blood Bank ");
        getContentPane().add(lbl_Footer1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 580, 430, -1));

        lbl_Footer2.setFont(new java.awt.Font("Gabriola", 1, 36)); // NOI18N
        lbl_Footer2.setText("@National Blood Transfusion Service");
        getContentPane().add(lbl_Footer2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 630, 500, -1));

        lbl_headline1.setFont(new java.awt.Font("Segoe UI", 1, 60)); // NOI18N
        lbl_headline1.setText("KINDNESS IS THE");
        getContentPane().add(lbl_headline1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, 520, -1));

        lbl_headline2.setFont(new java.awt.Font("Segoe UI", 1, 48)); // NOI18N
        lbl_headline2.setText("GREATEST WISDOM");
        getContentPane().add(lbl_headline2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 100, 490, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/Organization_Login_wallpaper.png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1000, 690));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btn_SignInActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_SignInActionPerformed
        // TODO add your handling code here:
         String RegNo,Password;
        boolean value;
        RegNo=txt_Ousername.getText();
        Password=pf_Opassword.getText();
        SelectedUser su=new SelectedUser();
        su.selectAuthenification(RegNo, Password);
        //C_Organization_Login ol=new C_Organization_Login();
        value=C_Organization_Login.OrganizationalLogin(RegNo, Password);
        if(value==true)
        {
            V_Home_page hp=new V_Home_page();
            hp.setVisible(true);
            this.setVisible(false);
        }
        else
        {
            JOptionPane.showMessageDialog(null, "Please Try Again Shortly !!!");
        }
    }//GEN-LAST:event_btn_SignInActionPerformed

    private void lbl_SignInMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_SignInMouseClicked
        // TODO add your handling code here:
        V_Organization_SignUp_Page os=new V_Organization_SignUp_Page();
        os.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_lbl_SignInMouseClicked

    private void lbl_Forgotten_passwordMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_Forgotten_passwordMouseClicked
        // TODO add your handling code here:
         VerificationPage v=new VerificationPage();
          v.setVisible(true);
         this.setVisible(false);
    }//GEN-LAST:event_lbl_Forgotten_passwordMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(V_Organization_login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(V_Organization_login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(V_Organization_login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(V_Organization_login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new V_Organization_login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_SignIn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel lbl_DisplayAccountStatus;
    private javax.swing.JLabel lbl_Footer1;
    private javax.swing.JLabel lbl_Footer2;
    private javax.swing.JLabel lbl_Forgotten_password;
    private javax.swing.JLabel lbl_Login;
    private javax.swing.JLabel lbl_SignIn;
    private javax.swing.JLabel lbl_headline1;
    private javax.swing.JLabel lbl_headline2;
    private javax.swing.JLabel lbl_password;
    private javax.swing.JLabel lbl_username;
    private javax.swing.JPasswordField pf_Opassword;
    private javax.swing.JTextField txt_Ousername;
    // End of variables declaration//GEN-END:variables
}
