/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package View;

import javax.swing.JOptionPane;
import Controller.*;
import Model.Validation;

/**
 *
 * @author Yasiru
 */
public class V_Organization_SignUp_Page extends javax.swing.JFrame {

    /**
     * Creates new form Camp_SignUp_Page
     */
    public V_Organization_SignUp_Page() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lbl_Registration = new javax.swing.JLabel();
        lbl_Organization = new javax.swing.JLabel();
        lbl_Registration_no = new javax.swing.JLabel();
        lbl_Account = new javax.swing.JLabel();
        lbl_OrganizationName = new javax.swing.JLabel();
        lbl_OrganizationalContactNo = new javax.swing.JLabel();
        lbl_OrganizationalEmail = new javax.swing.JLabel();
        lbl_Address = new javax.swing.JLabel();
        lbl_Password = new javax.swing.JLabel();
        lbl_subheading1 = new javax.swing.JLabel();
        lbl_ConfirmPassword = new javax.swing.JLabel();
        txt_Password = new javax.swing.JTextField();
        txt_MemberName = new javax.swing.JTextField();
        txt_ConfirmPassword = new javax.swing.JTextField();
        btn_Register = new javax.swing.JButton();
        lbl_TermsCondition = new javax.swing.JLabel();
        CheckBoxTerms = new javax.swing.JCheckBox();
        lbl_Member_name = new javax.swing.JLabel();
        txt_Registration_no = new javax.swing.JTextField();
        txt_OrganizationalName = new javax.swing.JTextField();
        txt_Organizational_Contact_No = new javax.swing.JTextField();
        txt_Organizational_Email = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        txt_Organizational_Address = new javax.swing.JTextArea();
        lbl_FaxNo = new javax.swing.JLabel();
        txt_Organizational_FaxNo = new javax.swing.JTextField();
        lbl_member_contactNo = new javax.swing.JLabel();
        lbl_Member_EMail = new javax.swing.JLabel();
        txt_Member_ContactNo = new javax.swing.JTextField();
        txt_MemberEmail = new javax.swing.JTextField();
        lbl_Footer = new javax.swing.JLabel();
        lbl_Logo = new javax.swing.JLabel();
        lbl_wallpaper = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1400, 750));
        setResizable(false);
        setSize(new java.awt.Dimension(1400, 750));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lbl_Registration.setFont(new java.awt.Font("Goudy Old Style", 1, 55)); // NOI18N
        lbl_Registration.setText("Registration");
        getContentPane().add(lbl_Registration, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 0, 270, -1));

        lbl_Organization.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        lbl_Organization.setText("Organization Details");
        getContentPane().add(lbl_Organization, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 60, 240, -1));

        lbl_Registration_no.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lbl_Registration_no.setText("Regstration No");
        getContentPane().add(lbl_Registration_no, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 130, 110, 30));

        lbl_Account.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        lbl_Account.setText("Account Authentication");
        getContentPane().add(lbl_Account, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 60, 290, -1));

        lbl_OrganizationName.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lbl_OrganizationName.setText("Name");
        getContentPane().add(lbl_OrganizationName, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 180, 110, 30));

        lbl_OrganizationalContactNo.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lbl_OrganizationalContactNo.setText("Contact No");
        getContentPane().add(lbl_OrganizationalContactNo, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 240, 110, 30));

        lbl_OrganizationalEmail.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lbl_OrganizationalEmail.setText("Organizational Email");
        getContentPane().add(lbl_OrganizationalEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 120, 190, -1));

        lbl_Address.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lbl_Address.setText("Address");
        getContentPane().add(lbl_Address, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 370, 70, 20));

        lbl_Password.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lbl_Password.setText("Password");
        getContentPane().add(lbl_Password, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 210, 140, -1));

        lbl_subheading1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lbl_subheading1.setText("Futher Communication Purposes Please Enter One Member Details");
        getContentPane().add(lbl_subheading1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 470, 590, 30));

        lbl_ConfirmPassword.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lbl_ConfirmPassword.setText("Confirm Password");
        getContentPane().add(lbl_ConfirmPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 300, 180, -1));

        txt_Password.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        getContentPane().add(txt_Password, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 240, 470, 40));

        txt_MemberName.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        getContentPane().add(txt_MemberName, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 520, 440, 40));

        txt_ConfirmPassword.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        getContentPane().add(txt_ConfirmPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 340, 470, 40));

        btn_Register.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        btn_Register.setText("REGISTER");
        btn_Register.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_RegisterActionPerformed(evt);
            }
        });
        getContentPane().add(btn_Register, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 560, 210, 60));

        lbl_TermsCondition.setFont(new java.awt.Font("Segoe Script", 1, 18)); // NOI18N
        lbl_TermsCondition.setText("Terms and Conditions");
        lbl_TermsCondition.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbl_TermsConditionMouseClicked(evt);
            }
        });
        getContentPane().add(lbl_TermsCondition, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 490, 240, -1));

        CheckBoxTerms.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        CheckBoxTerms.setText("I Agreed to Terms and Conditions.");
        getContentPane().add(CheckBoxTerms, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 440, 330, -1));

        lbl_Member_name.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lbl_Member_name.setText("Member Name");
        getContentPane().add(lbl_Member_name, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 530, -1, -1));

        txt_Registration_no.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        getContentPane().add(txt_Registration_no, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 122, 440, 40));

        txt_OrganizationalName.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        getContentPane().add(txt_OrganizationalName, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 172, 440, 40));

        txt_Organizational_Contact_No.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        getContentPane().add(txt_Organizational_Contact_No, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 232, 440, 40));

        txt_Organizational_Email.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        getContentPane().add(txt_Organizational_Email, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 160, 470, 40));

        txt_Organizational_Address.setColumns(20);
        txt_Organizational_Address.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        txt_Organizational_Address.setRows(5);
        jScrollPane1.setViewportView(txt_Organizational_Address);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 370, 440, 60));

        lbl_FaxNo.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lbl_FaxNo.setText("Fax No");
        getContentPane().add(lbl_FaxNo, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 300, 90, 30));

        txt_Organizational_FaxNo.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        getContentPane().add(txt_Organizational_FaxNo, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 292, 440, 40));

        lbl_member_contactNo.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lbl_member_contactNo.setText("Contact No");
        getContentPane().add(lbl_member_contactNo, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 590, -1, -1));

        lbl_Member_EMail.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lbl_Member_EMail.setText("Personal Email");
        getContentPane().add(lbl_Member_EMail, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 640, -1, -1));

        txt_Member_ContactNo.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        getContentPane().add(txt_Member_ContactNo, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 580, 440, 40));

        txt_MemberEmail.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        getContentPane().add(txt_MemberEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 642, 440, 40));

        lbl_Footer.setFont(new java.awt.Font("Goudy Old Style", 1, 18)); // NOI18N
        lbl_Footer.setText("National Blood Bank  @ National Blood Transfusion Service");
        getContentPane().add(lbl_Footer, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 710, 480, -1));

        lbl_Logo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/Logo_size_3.png"))); // NOI18N
        getContentPane().add(lbl_Logo, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 690, 50, 50));

        lbl_wallpaper.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/Organization_SignUp_wallpaper.png"))); // NOI18N
        getContentPane().add(lbl_wallpaper, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1400, 750));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btn_RegisterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_RegisterActionPerformed
        // TODO add your handling code here:
        try
        {
        boolean value,evalid1,evalid2;
        int Organizational_Contact_No,Fax_no,Member_Contact_no;
        String RegNo,Name,Address,Member_Name,Member_Email,Organizational_Email,Password,Confirm_Password;
        RegNo=txt_Registration_no.getText();
        Name=txt_OrganizationalName.getText();
        Organizational_Contact_No=Integer.parseInt(txt_Organizational_Contact_No.getText());
        Fax_no=Integer.parseInt(txt_Organizational_FaxNo.getText());
        Address=txt_Organizational_Address.getText();
        Member_Name=txt_MemberName.getText();
        Member_Contact_no=Integer.parseInt(txt_Member_ContactNo.getText());
        Member_Email=txt_MemberEmail.getText();
        Organizational_Email=txt_Organizational_Email.getText();
        Password=txt_Password.getText();
        Confirm_Password=txt_ConfirmPassword.getText();
        
          Validation v=new Validation();
          evalid1= Validation.EmailValidation(Member_Email);
          evalid2= Validation.EmailValidation(Member_Email);
          if(evalid1==true)
          {
            if(evalid2==true)
             {
                    
        if(Password.equals(Confirm_Password))
        {
              if(this.CheckBoxTerms.isSelected())
              {
                  // C_Organization_registration or=new C_Organization_registration();
                   value=C_Organization_registration.OrganizationRegistration(RegNo, Name, Organizational_Contact_No, Fax_no, Address, Member_Name, Member_Contact_no, Member_Email, Organizational_Email, Password);
                    if(value==true)
                           {
                            V_Organization_login h1=new V_Organization_login();
                            h1.setVisible(true);
                            this.setVisible(false);
                           }
                           else
                           {
                            JOptionPane.showMessageDialog(null, "Please try again shortly !!!");
                             V_Organization_login h1=new V_Organization_login();
                            h1.setVisible(true);
                            this.setVisible(false);
                           }
              }
              else
              {
                  JOptionPane.showMessageDialog(null,"Please Agree to Terms and Conditions");
              }
        }
        else
        {
             JOptionPane.showMessageDialog(null,"Please Enter Password Correctly Again");
        }
              }
              else
              {
                  JOptionPane.showMessageDialog(null, "Please enter valid Member Email");
              }
          }
          else
          {
              JOptionPane.showMessageDialog(null, "Please enter valid Organizational Email");
          }
        
        
        }
        catch(Exception ex)
        {
             JOptionPane.showMessageDialog(null, ex);
        }
    }//GEN-LAST:event_btn_RegisterActionPerformed

    private void lbl_TermsConditionMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_TermsConditionMouseClicked
        // TODO add your handling code here:
        V_TermsAndConditions tc=new V_TermsAndConditions();
        tc.setVisible(true);
        
    }//GEN-LAST:event_lbl_TermsConditionMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(V_Organization_SignUp_Page.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(V_Organization_SignUp_Page.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(V_Organization_SignUp_Page.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(V_Organization_SignUp_Page.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new V_Organization_SignUp_Page().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox CheckBoxTerms;
    private javax.swing.JButton btn_Register;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lbl_Account;
    private javax.swing.JLabel lbl_Address;
    private javax.swing.JLabel lbl_ConfirmPassword;
    private javax.swing.JLabel lbl_FaxNo;
    private javax.swing.JLabel lbl_Footer;
    private javax.swing.JLabel lbl_Logo;
    private javax.swing.JLabel lbl_Member_EMail;
    private javax.swing.JLabel lbl_Member_name;
    private javax.swing.JLabel lbl_Organization;
    private javax.swing.JLabel lbl_OrganizationName;
    private javax.swing.JLabel lbl_OrganizationalContactNo;
    private javax.swing.JLabel lbl_OrganizationalEmail;
    private javax.swing.JLabel lbl_Password;
    private javax.swing.JLabel lbl_Registration;
    private javax.swing.JLabel lbl_Registration_no;
    private javax.swing.JLabel lbl_TermsCondition;
    private javax.swing.JLabel lbl_member_contactNo;
    private javax.swing.JLabel lbl_subheading1;
    private javax.swing.JLabel lbl_wallpaper;
    private javax.swing.JTextField txt_ConfirmPassword;
    private javax.swing.JTextField txt_MemberEmail;
    private javax.swing.JTextField txt_MemberName;
    private javax.swing.JTextField txt_Member_ContactNo;
    private javax.swing.JTextField txt_OrganizationalName;
    private javax.swing.JTextArea txt_Organizational_Address;
    private javax.swing.JTextField txt_Organizational_Contact_No;
    private javax.swing.JTextField txt_Organizational_Email;
    private javax.swing.JTextField txt_Organizational_FaxNo;
    private javax.swing.JTextField txt_Password;
    private javax.swing.JTextField txt_Registration_no;
    // End of variables declaration//GEN-END:variables
}
