/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package View;

import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.Date;
import Controller.C_Transcation;
import javax.swing.JOptionPane;

/**
 * @author Yasiru
 * contact me : https://linktr.ee/yasiruchamuditha for more information.
 */
public class V_Transcation extends javax.swing.JFrame {

    /**
     * Creates new form V_Transcation
     */
    public V_Transcation() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lbl_Transcation = new javax.swing.JLabel();
        lbl_PatientNIC = new javax.swing.JLabel();
        lbl_PatientName = new javax.swing.JLabel();
        lbl_PatientContactNo = new javax.swing.JLabel();
        lbl_Date = new javax.swing.JLabel();
        lbl_Time = new javax.swing.JLabel();
        lbl_HospitalLinked = new javax.swing.JLabel();
        txt_PatientNIC = new javax.swing.JTextField();
        txt_PatientName = new javax.swing.JTextField();
        txt_PatientContactNo = new javax.swing.JTextField();
        txt_Time = new javax.swing.JTextField();
        DatePickerDate = new org.jdesktop.swingx.JXDatePicker();
        txt_HospitalLinked = new javax.swing.JTextField();
        lbl_WeightOfBags = new javax.swing.JLabel();
        lbl_Footer = new javax.swing.JLabel();
        txt_WeightOfBags = new javax.swing.JTextField();
        btn_Submit = new javax.swing.JButton();
        lbl_Logo = new javax.swing.JLabel();
        lbl_issuedOfficerID = new javax.swing.JLabel();
        lbl_NoOfBags = new javax.swing.JLabel();
        txt_IssuedEmployeeId = new javax.swing.JTextField();
        txt_NoOfBags = new javax.swing.JTextField();
        lbl_Blood_Group = new javax.swing.JLabel();
        cmb_BloodGroup = new javax.swing.JComboBox<>();
        lbl_Back = new javax.swing.JLabel();
        lbl_wallpaper = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(1400, 800));
        setMinimumSize(new java.awt.Dimension(1400, 800));
        setResizable(false);
        setSize(new java.awt.Dimension(1400, 800));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lbl_Transcation.setFont(new java.awt.Font("Segoe UI", 1, 48)); // NOI18N
        lbl_Transcation.setText("Blood Transcations");
        getContentPane().add(lbl_Transcation, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 0, 455, -1));

        lbl_PatientNIC.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lbl_PatientNIC.setText("Patient NIC");
        getContentPane().add(lbl_PatientNIC, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 110, 100, -1));

        lbl_PatientName.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lbl_PatientName.setText("Patient Name");
        getContentPane().add(lbl_PatientName, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 190, 110, -1));

        lbl_PatientContactNo.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lbl_PatientContactNo.setText("Patient Contact No");
        getContentPane().add(lbl_PatientContactNo, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 260, 140, -1));

        lbl_Date.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lbl_Date.setText("Date");
        getContentPane().add(lbl_Date, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 340, 70, -1));

        lbl_Time.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lbl_Time.setText("Time");
        getContentPane().add(lbl_Time, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 420, 70, -1));

        lbl_HospitalLinked.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lbl_HospitalLinked.setText("Hospitial Linked");
        getContentPane().add(lbl_HospitalLinked, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 290, 120, -1));

        txt_PatientNIC.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        getContentPane().add(txt_PatientNIC, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 100, 410, 40));

        txt_PatientName.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        getContentPane().add(txt_PatientName, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 170, 410, 40));

        txt_PatientContactNo.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        getContentPane().add(txt_PatientContactNo, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 250, 410, 40));

        txt_Time.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        getContentPane().add(txt_Time, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 410, 410, 40));
        getContentPane().add(DatePickerDate, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 330, 410, 40));

        txt_HospitalLinked.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        getContentPane().add(txt_HospitalLinked, new org.netbeans.lib.awtextra.AbsoluteConstraints(920, 280, 410, 40));

        lbl_WeightOfBags.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lbl_WeightOfBags.setText("Weight of bags");
        getContentPane().add(lbl_WeightOfBags, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 110, 110, -1));

        lbl_Footer.setFont(new java.awt.Font("Goudy Old Style", 1, 18)); // NOI18N
        lbl_Footer.setText("National Blood Bank @ National Blood Transfusion Service");
        getContentPane().add(lbl_Footer, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 740, 440, -1));

        txt_WeightOfBags.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        getContentPane().add(txt_WeightOfBags, new org.netbeans.lib.awtextra.AbsoluteConstraints(920, 100, 410, 40));

        btn_Submit.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        btn_Submit.setText("SUBMIT");
        btn_Submit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_SubmitActionPerformed(evt);
            }
        });
        getContentPane().add(btn_Submit, new org.netbeans.lib.awtextra.AbsoluteConstraints(970, 490, 290, 60));

        lbl_Logo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/Logo_size_3.png"))); // NOI18N
        getContentPane().add(lbl_Logo, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 720, -1, 50));

        lbl_issuedOfficerID.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lbl_issuedOfficerID.setText("Issued Officer Id");
        getContentPane().add(lbl_issuedOfficerID, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 380, -1, -1));

        lbl_NoOfBags.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lbl_NoOfBags.setText("No_Of_Bags");
        getContentPane().add(lbl_NoOfBags, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 200, -1, -1));

        txt_IssuedEmployeeId.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        getContentPane().add(txt_IssuedEmployeeId, new org.netbeans.lib.awtextra.AbsoluteConstraints(920, 370, 410, 40));

        txt_NoOfBags.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        getContentPane().add(txt_NoOfBags, new org.netbeans.lib.awtextra.AbsoluteConstraints(920, 190, 410, 40));

        lbl_Blood_Group.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lbl_Blood_Group.setText("Blood  Group");
        getContentPane().add(lbl_Blood_Group, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 500, -1, -1));

        cmb_BloodGroup.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Please Select", "A+", "A-", "B+", "B-", "AB+", "AB-", "O+", "O-" }));
        getContentPane().add(cmb_BloodGroup, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 492, 410, 40));

        lbl_Back.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        lbl_Back.setText("Back");
        lbl_Back.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbl_BackMouseClicked(evt);
            }
        });
        getContentPane().add(lbl_Back, new org.netbeans.lib.awtextra.AbsoluteConstraints(1290, 700, 110, 70));

        lbl_wallpaper.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/transcationWallpaper.jpg"))); // NOI18N
        getContentPane().add(lbl_wallpaper, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1400, 800));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btn_SubmitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_SubmitActionPerformed
        // TODO add your handling code here:
        int Patient_Contact_No,No_Of_Bags;
        boolean result,stock;
        String Patient_NIC,Patient_Name,Date,Time,Blood_Group,Hospital_Linked,Incharge_Officer_ID;
        float Weight_Of_Blood;
        
        Patient_NIC=txt_PatientNIC.getText();
        Patient_Name=txt_PatientName.getText();
        Patient_Contact_No=Integer.parseInt(txt_PatientContactNo.getText());
         Date Date1=DatePickerDate.getDate();
        //create object in date format class and call SimpleDateFormat method
        DateFormat dformat=new SimpleDateFormat("yyyy-MM-dd");
        //assign formated date to dob variable
        Date=dformat.format(Date1);
        Time=txt_Time.getText();
        Blood_Group=cmb_BloodGroup.getSelectedItem().toString();
        Weight_Of_Blood=Float.parseFloat(txt_WeightOfBags.getText());
        No_Of_Bags=Integer.parseInt(txt_NoOfBags.getText());
        Hospital_Linked=txt_HospitalLinked.getText();
        Incharge_Officer_ID=txt_IssuedEmployeeId.getText();
        
        C_Transcation tr=new C_Transcation();
        result=C_Transcation.Transcation(Patient_NIC,Patient_Name,Patient_Contact_No,Date,Time,Blood_Group,Weight_Of_Blood,No_Of_Bags,Hospital_Linked,Incharge_Officer_ID);
        stock=C_Transcation.updateStockTranscation(No_Of_Bags, Blood_Group);
        if(result==true)
        {
            if(stock==true)
            {
                JOptionPane.showMessageDialog(null,"Transcation Succesfully Registered");
                txt_PatientNIC.setText(null);
                txt_PatientName.setText(null);
                txt_PatientContactNo.setText(null);
                txt_Time.setText(null);
                cmb_BloodGroup.setSelectedIndex(0);
                txt_WeightOfBags.setText(null);
                txt_NoOfBags.setText(Time);
                txt_HospitalLinked.setText(null);
                txt_IssuedEmployeeId.setText(null);
            }
            else
            {
                JOptionPane.showMessageDialog(null,"Storage is not updated,Please Immediately Contact Admin panel for Responce");
            }
        }
        else
        {
            JOptionPane.showMessageDialog(null,"Please Try Again shortly");
        }
   
    }//GEN-LAST:event_btn_SubmitActionPerformed

    private void lbl_BackMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_BackMouseClicked
        // TODO add your handling code here:
        V_home_admin ha=new V_home_admin();
        ha.setVisible(true);
        this.dispose();;
    }//GEN-LAST:event_lbl_BackMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(V_Transcation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(V_Transcation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(V_Transcation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(V_Transcation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new V_Transcation().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private org.jdesktop.swingx.JXDatePicker DatePickerDate;
    private javax.swing.JButton btn_Submit;
    private javax.swing.JComboBox<String> cmb_BloodGroup;
    private javax.swing.JLabel lbl_Back;
    private javax.swing.JLabel lbl_Blood_Group;
    private javax.swing.JLabel lbl_Date;
    private javax.swing.JLabel lbl_Footer;
    private javax.swing.JLabel lbl_HospitalLinked;
    private javax.swing.JLabel lbl_Logo;
    private javax.swing.JLabel lbl_NoOfBags;
    private javax.swing.JLabel lbl_PatientContactNo;
    private javax.swing.JLabel lbl_PatientNIC;
    private javax.swing.JLabel lbl_PatientName;
    private javax.swing.JLabel lbl_Time;
    private javax.swing.JLabel lbl_Transcation;
    private javax.swing.JLabel lbl_WeightOfBags;
    private javax.swing.JLabel lbl_issuedOfficerID;
    private javax.swing.JLabel lbl_wallpaper;
    private javax.swing.JTextField txt_HospitalLinked;
    private javax.swing.JTextField txt_IssuedEmployeeId;
    private javax.swing.JTextField txt_NoOfBags;
    private javax.swing.JTextField txt_PatientContactNo;
    private javax.swing.JTextField txt_PatientNIC;
    private javax.swing.JTextField txt_PatientName;
    private javax.swing.JTextField txt_Time;
    private javax.swing.JTextField txt_WeightOfBags;
    // End of variables declaration//GEN-END:variables
}
